export { Hero } from "./Hero";
export { About } from "./About";
export { Skills } from "./Skills";
export { Projects } from "./Projects";
export { Education } from "./Education";
export { Certificates } from "./Certificates";
export { ProfessionalExperienceSection as ProfessionalExperience } from "./ProfessionalExperience";
export { ExtracurricularActivities } from "./ExtracurricularActivities";
export { Contact } from "./Contact";
export { Badges } from "./Badges";
export { Thesis } from "./Thesis";
export { Courses } from "./Courses";
